language: php
sudo: false
php:
    - 8.0
cache:
    directories:
        - $HOME/.composer/cache
addons:
    sonarcloud:
        organization: "quillstack"
        token:
            secure: "JC9HLkt651WaTQh335FYGyK8OqHULQWI15NE3fMjZQXsqAa+Ur22bhgrScCjQVrnYFlHdXYIdCTtoztN17/7ERZvcFk2RS/Va/5UzPgN2OZNzSR7pRhMELIfjufEmlwMHmi6LyAkmgGTUUfe6qa37NstOcdMc+EpMBNDDBe+e+MmYKHt/ltxnpTyUtrvqGeYkv2ywD6D1H5W2VHZKRuaOSgB54NK7wbrbDgkrwSNGz0ZLPzvyIBm9W2govKyb4+yoTLJAdJPOMfcp4V4Ts9lhQXuzF7cOJ/P9VZ1zhYqT1gJOFK+ONBsCEQdutT+Xco9DUe0PTyecFVfHl2ev1yYaer8nK1BwVRRFZfuEaegsRBYyiKKPGPhaMthUCE+XWQea51BEZ9gxawtOaOVLX8wUPA8KqH9u5HPmh5v/2UrEIw64CW/5dNZUTfyjklzOszZRVawRi9pgUJeQnCWApyQ0SEpLhzu3UFs3eQ5G2JKkdWQJmnI7OODXSgNEyQi39Ff7JGVAjU0wLVixe/hNWQMrCtvpfvv3VAYQbp8EtQlRqvdI3PM1tdk9Z6+fpV3CqFY1RWl4N+04jj1gg/7qBaGfbmHqFwONsocEcAmtyDyaJBwvaFNgtWWbwU71rIbIBIM82lqV964cCuuqWxzF+isz8lZUH9pgN4j6hx9XWuzDQE="
git:
    depth: false
install: composer update --no-interaction --no-suggest --no-progress
script:
    - sonar-scanner
